### ISSUE TITLE
Not working on Windows 10 ?

### ISSUE THREAD

**Issue by ghost** [gcalderone/CMPFit.jl#3]
Hi,

Is CMPFit supposed to work on windows 10 64bit ?

I use it since some time on OsX, but try today to install it on Windows 10 and got the following error (fresh Julia 1.6.3 install with only CMPFit 0.3.2 as installed package) when trying to run the Readme example : 

In Juno
`package versions...
   Installed CMPFit ─ v0.3.2
  Downloaded artifact: libmpfit
    Updating `C:\Users\geops\.julia\environments\v1.6\Project.toml`
  [a5944310] + CMPFit v0.3.2
    Updating `C:\Users\geops\.julia\environments\v1.6\Manifest.toml`
  [a5944310] + CMPFit v0.3.2
Precompiling project...
  1 dependency successfully precompiled in 1 seconds (54 already precompiled)
An error occurred during `mpfit` call:
ErrorException("could not load library \"C:\\Users\\geops\\.julia\\artifacts\\21ba4174eb6b3f2b3191bdcc9cb48d393e4bf7a6\\libmpfit.dll\"\nAccès refusé. ")`

And in command prompt :
`ERROR: LoadError: An error occurred during `mpfit` call.
.....
Stacktrace:
.....caused by: could not load library "C:\Users\geops\.julia\artifacts\21ba4174eb6b3f2b3191bdcc9cb48d393e4bf7a6\libmpfit.dll"
%1 n’est pas une application Win32 valide.`

Any hint on a workaround ?

Thx

**Comment by gcalderone** [comment]
Hi,
yes, CMPFit is supposed to work on windows as well.  However my experience on microsoft systems is definitely limited since I don't even have access to a windows machine.
I'll try to investigate and come back to you.

**Comment by gcalderone** [comment]
I set up CI on Windows, and the problem seems to be solved now.
Try upgrading to the new v0.3.3.

**Comment by gcalderone** [comment]
Also, ensure that the DLL file has the "Read & execute" permission enabled.
Apparently this problem affects only julia v1.6 on windows (not v1.5).

The path of the DLL is something similar to: `C:\Users\Giorgio\.julia\artifacts\7223c3b488dbc040e43fd4c14e8215d13d3d43f2\libmpfit.dll`

**Comment by ghost** [comment]
Wonderful,

That did the trick.
I indeed had to manually change permissions on the DLL file.


Many thanks,
