### ISSUE TITLE
Make compatible with 1.8 MacOS ARM ?

### ISSUE THREAD

**Issue by jnouet** [gcalderone/CMPFit.jl#4]
Hello,

This package is not working with Julia natively running on M1/M2 chipsets (I guess libraries should be re-compiled for this architecture, as it works under Rosetta).

Any plans on an upcoming update ?

All the best,

**Comment by gcalderone** [comment]
Yes, a library should be compiled for each architecture until I will find the time to port the C code to Julia (and unfortunately this is not going to happen anytime soon...).
Besides, I don't even have the hardware to compile and test.

PR with new artifacts are welcome!

**Comment by jnouet** [comment]
Ok,

Let me know if I could be of any help : I am not familiar with C but can try to compile it (if you can give me hints on the procedure).

**Comment by gcalderone** [comment]
Here's what I do on linux to generate `libmpfit.so`:
```
wget https://pages.physics.wisc.edu/~craigm/idl/down/cmpfit-1.4.tar.gz
tar xvf cmpfit-1.4.tar.gz 
cd cmpfit-1.4
gcc -O3 -fPIC -shared mpfit.c -o libmpfit.so
```
but I don't know if it would be the same on your platform.

Also, we need to specify the architecture for the artifact.  Valid options are:
```
using Pkg
Pkg.BinaryPlatforms.Linux(:x86_64)
Pkg.BinaryPlatforms.MacOS(:x86_64)
Pkg.BinaryPlatforms.Windows(:x86_64)
```
In your case it would be something like `Pkg.BinaryPlatforms.MacOS(????)`, but I don't know what to put in place of `???`.

**Comment by jnouet** [comment]
Well, it seems to work I could generate a .dylib file (replacing -shared by -dynamiclib). 
The later is working on a local copy of CMPFit.

[libmpfit_osx_arm.dylib.zip](https://github.com/gcalderone/CMPFit.jl/files/9664390/libmpfit_osx_arm.dylib.zip)

I am not sure how I can answer your second question : where should I look ?
From here :
https://github.com/JuliaLang/julia/issues/36617
I would say maybe : MacOS(:aarch64) ?

**Comment by gcalderone** [comment]
I added your binary file to the list of available artifacts in the [Adding_aarch64_macos](https://github.com/gcalderone/CMPFit.jl/tree/Adding_aarch64_macos) branch.  Please test it and let me know if it works for you.

**Comment by jnouet** [comment]
using:

`(@v1.8) pkg> add CMPFit#Adding_aarch64_macos`

CMPFit properly installs and works

**Comment by gcalderone** [comment]
Have you tried `]test CMPFit`?

**Comment by jnouet** [comment]
I get:

(@v1.8) pkg> test CMPFit
     Testing CMPFit
      Status `/private/var/folders/h6/c0sgc7_x5wv54s1m8z0yj5dc0000gn/T/jl_EPI0fY/Project.toml`
  [a5944310] CMPFit v0.3.3 `https://github.com/gcalderone/CMPFit.jl.git#Adding_aarch64_macos`
  [44cfe95a] Pkg v1.8.0 `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [8dfed614] Test `@stdlib/Test`
      Status `/private/var/folders/h6/c0sgc7_x5wv54s1m8z0yj5dc0000gn/T/jl_EPI0fY/Manifest.toml`
  [a5944310] CMPFit v0.3.3 `https://github.com/gcalderone/CMPFit.jl.git#Adding_aarch64_macos`
  [0dad84c5] ArgTools v1.1.1 `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [f43a241f] Downloads v1.6.0 `@stdlib/Downloads`
  [7b1f6079] FileWatching `@stdlib/FileWatching`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL v0.6.3 `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [ca575930] NetworkOptions v1.2.0 `@stdlib/NetworkOptions`
  [44cfe95a] Pkg v1.8.0 `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA v0.7.0 `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [fa267f1f] TOML v1.0.0 `@stdlib/TOML`
  [a4e569a6] Tar v1.10.0 `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [deac9b47] LibCURL_jll v7.84.0+0 `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll v1.10.2+0 `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll v2.28.0+0 `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll v2022.2.1 `@stdlib/MozillaCACerts_jll`
  [83775a58] Zlib_jll v1.2.12+3 `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll v1.48.0+0 `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll v17.4.0+0 `@stdlib/p7zip_jll`
     Testing Running tests...
[ Info: /Users/julius/.julia/artifacts/1793c8cbba90868a5ea37c9b2351cb6392b62294/libmpfit_osx_arm.dylib
     Testing CMPFit tests passed

On a fresh install, when I run:

`(@v1.8) pkg> add CMPFit#Adding_aarch64_macos


Sys.ARCH
using CMPFit


x = [-1.7237128E+00,1.8712276E+00,-9.6608055E-01,
    -2.8394297E-01,1.3416969E+00,1.3757038E+00,
    -1.3703436E+00,4.2581975E-02,-1.4970151E-01,
    8.2065094E-01]

y = [-4.4494256E-02,8.7324673E-01,7.4443483E-01,
     4.7631559E+00,1.7187297E-01,1.1639182E-01,
     1.5646480E+00,5.2322268E+00,4.2543168E+00,
     6.2792623E-01]

e = fill(0., size(y)) .+ 0.5

function GaussModel(x::Vector{Float64}, p::Vector{Float64})
  sig2 = p[4] * p[4]
  xc = @. x - p[3]
  model = @. p[2] * exp(-0.5 * xc * xc / sig2) + p[1]
  return model
end

param = [0.0, 1.0, 1.0, 1.0]

res = cmpfit(x, y, e, GaussModel, param);
println(res)`
 
I get:

(@v1.8) pkg> add CMPFit#Adding_aarch64_macos
    Updating git-repo `https://github.com/gcalderone/CMPFit.jl.git`
   Resolving package versions...
    Updating `~/.julia/environments/v1.8/Project.toml`
  [a5944310] + CMPFit v0.3.3 `https://github.com/gcalderone/CMPFit.jl.git#Adding_aarch64_macos`
    Updating `~/.julia/environments/v1.8/Manifest.toml`
  [a5944310] + CMPFit v0.3.3 `https://github.com/gcalderone/CMPFit.jl.git#Adding_aarch64_macos`
  CMPFit ver. = 1.4
      STATUS = 1
  CHI-SQUARE = 10.350032    (6 DOF)
        NPAR = 4
       NFREE = 4
     NPEGGED = 0
       NITER = 28
        NFEV = 139
Elapsed time = 0.069203 s

  P[1] = 0.480443 +/- 0.232235
  P[2] = 4.550752 +/- 0.395434
  P[3] = -0.062562 +/- 0.074715
  P[4] = 0.397472 +/- 0.089996

julia> 
julia>   CMPFit ver. = 1.4
      STATUS = 1
  CHI-SQUARE = 10.350032    (6 DOF)
        NPAR = 4
       NFREE = 4
     NPEGGED = 0
       NITER = 28
        NFEV = 139
Elapsed time = 0.069203 s

  P[1] = 0.480443 +/- 0.232235
  P[2] = 4.550752 +/- 0.395434
  P[3] = -0.062562 +/- 0.074715
  P[4] = 0.397472 +/- 0.089996

**Comment by gcalderone** [comment]
Looks fine. I will merge it into version 0.3.4, and notify here once registered.

**Comment by jnouet** [comment]
Nice,

Many thanks.

**Comment by gcalderone** [comment]
CMPFit v0.3.4 is now registered.
